name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Album-Api/Album-Api.sln
    - name: Build
      run: dotnet build Album-Api/Album-Api.sln --no-restore
    - name: Test
      run: dotnet test Album-Api/Album.Api.Tests/Album.Api.Tests.csproj --verbosity normal

  build-docker:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t album-api .

    - name: Tag Docker image
      run: docker tag album-api:latest 934870780723.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:${{ github.run_number }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 934870780723.dkr.ecr.us-east-1.amazonaws.com

    - name: Push Docker image to ECR
      run: docker push 934870780723.dkr.ecr.us-east-1.amazonaws.com/cnsd/album:${{ github.run_number }}
