# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Album-Api/Album-Api.sln
    - name: Build
      run: dotnet build Album-Api/Album-Api.sln --no-restore
    - name: Test
      run: dotnet test Album-Api/Album.Api.Tests/Album.Api.Tests.csproj --verbosity normal
  build-docker:
      runs-on: ubuntu-latest
      needs: build
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t album-api .
